#!/bin/bash

rp -rf iid-bits
mkdir iid-bits

for bits in {16..0}; do
	order=$((16 - bits))
	orderString=$(printf "%02d" $order)
	echo "$bits : $order : $orderString"
	if [[ -e results-measurements-random_memaccess-depth-${bits}/jent-raw-noise-sd.bin ]] ; then
		cp -a results-measurements-random_memaccess-depth-${bits}/jent-raw-noise-sd.bin iid-bits/${orderString}-jent-${bits}-sd.bin
	fi
done
